### ISSUE TITLE
Autosave on changes is disabled

### ISSUE THREAD

**Issue by surendrajat** [NickRimmer/insomnia-plugin-free-sync#20]
Thanks for this plugin. Save/Load work fine now.

Although the Autosave feature didn't. I thought it's not working just for me, but looks like it is disabled in the code as well:

https://github.com/NickRimmer/insomnia-plugin-free-sync/blob/f0e743d7c54f8771ffab87a5335785ae92150426/src/components/configuration-dialog.tsx#L73

Is it still being worked out?

**Comment by NickRimmer** [comment]
Yep, it is not implemented yet. But it was my initial reason for this plugin and I will add it

**Comment by funkysoul** [comment]
Hi Nick, thanks for the great plugin.
Are you still planning on doing the autosave option? or isn't it possible at all?

**Comment by NickRimmer** [comment]
Yep, sorry for such long answer. I will check what was the last time I've made. I still believe it could be a nice feature (;

**Comment by NickRimmer** [comment]
Hey! Just a heads-up that I'm closing old tickets and archiving this repo. I've started working on my own client, where I'll be applying all the ideas I wanted to bring here 😊

It's called [RestApia](https://www.restapia.app/). Feel free to check it out!
